### PR TITLE
Store prebuild jars in repo

### PR DESCRIPTION
**Pull request by MrAn0nym**
If you're planning to merge this i'll also create pr's for the 1.17, 1.18 branches and the same on the iris repo ^^

### CODE REVIEW

**Comment by K0-RR** [comment]
Uhhh you should squash these commits.

But why even do this? Artifacts can already be downloaded from Actions.

**Comment by MrAn0nym** [comment]
> Uhhh you should squash these commits.

Not enabled afaik 
image

> But why even do this? Artifacts can already be downloaded from Actions.

This would allow to have one persistent link and you woudn't need a github account to download it

**Comment by Justsnoopy30** [comment]
What exactly does this do?

**Comment by MenacingPerson** [comment]
This can be done through nightly.link

**Comment by MrAn0nym** [comment]
> This can be done through nightly.link

good to know that. thx ^^

**Pull request closed without merging**
